### ISSUE TITLE
SEC-4941 - XSS on /#calendarevent/view/ page

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#116]
XSS on /#calendarevent/view/ page

Steps to reproduce:

1. Visit this page https://partners.acronis.com/#manage/calendar/eventscalendar
2. Click add event to any day
3. Type this payload <img src=x onerror=confirm(2022)> in the description input
4. Visit this page https://partners.acronis.com/#calendarevent/view/ and see payload executed

Fix: encode untrusted input according to the rendering context

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, I have checked the above security issue and JS is getting executed by adding script in the description field.
![image](https://user-images.githubusercontent.com/102346181/184293223-ee25949a-31cd-479e-876f-58b7dfe1722a.png)

**Comment by MeghanaThakekar** [comment]
@PuneetRevclerx - not able to reproduce, please check on main
![image](https://user-images.githubusercontent.com/6465588/187393225-3885a419-72b9-49fe-9aa6-e19ca8df56f5.png)
![image](https://user-images.githubusercontent.com/6465588/187393315-66b21ce6-7713-4f6b-a532-ad7922b3d831.png)

**Comment by PuneetRevclerx** [comment]
@MeghanaThakekar mam, some of the XSS payloads that I was using previously are not working now. But, if we add ("Test <script>alert('XSS on Calender event')</script>") in the description through "api/AddCalendarEvent" then JS is still getting executed. 
![image](https://user-images.githubusercontent.com/102346181/187405378-1d561940-1e80-40c8-8e7b-d6d52085712f.png)

**Comment by MeghanaThakekar** [comment]
@PuneetRevclerx - fixed
branch : https://pr-52090.dvl.amp.vg/

**Comment by PuneetRevclerx** [comment]
@MeghanaThakekar mam, I have checked the above security issue on the given branch (https://pr-52090.dvl.amp.vg/) and after adding (<script>alert(1)</script>) in the description, when I open the event again it shows below results instead of showing event details.

![image](https://user-images.githubusercontent.com/102346181/189576049-cf6a95ff-9f9b-4319-9366-f237361e3ee2.png)

Click on the View button>> select edit event

![image](https://user-images.githubusercontent.com/102346181/189576355-c3980d40-cfcb-44d4-b236-1ba6eabb2d3b.png)

**Comment by MeghanaThakekar** [comment]
@PuneetRevclerx - fixed

**Comment by PuneetRevclerx** [comment]
@MeghanaThakekar mam, as mentioned on the PR, I checked above security issue again. JS is not getting executed on the calendar event. But, after adding ("Test <script>alert('XSS on Calendar event')</script>") in the description. If I click on the event again to view it then it shows some text as shown in the screenshot. This issue was fixed earlier but now facing it again

![image](https://user-images.githubusercontent.com/102346181/197718668-90ad693d-6c7a-493d-a46e-1ea278995db3.png)

**Comment by MeghanaThakekar** [comment]
@PuneetRevclerx - fixed

**Comment by PuneetRevclerx** [comment]
@MeghanaThakekar mam, @sunrao sir, I have checked above security issue on given branch (https://pr-52090.dvl.amp.vg/) and it's working as expected now.

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on Acronis Production and it's working as expected now.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify.

**Comment by prashantjadhav92** [comment]
The fix has been verified by the client.
