### ISSUE TITLE
SEC-4935 - IDOR via /calendarevent/view/<id>

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#134]
IDOR on /calendarevent/view/<id>

Steps to reproduce:
Open: view-source:https://partners.acronis.com/calendarevent/view/<id>  with id of calendar event from any other organization and see information about the event.

Example: https://partners.acronis.com/calendarevent/view/11

Fix: it must not be possible to access data of other organizations

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 Sir, I have checked above security issue, am not able to access data of calendarevents created by other organization's user.
Kindly provide screen recording or some additional info, so I can reproduce the issue on my end.

**Comment by prashantjadhav92** [comment]
@IshantRevclerx can you please check this on Acronis install once? The client is still able to reproduce this issue.

You can just open in the browser the following: view-source:https://partners.acronis.com/calendarevent/view/11 and see data accessible:
![scrot_selection_Aug102022_012154](https://user-images.githubusercontent.com/31324885/191350099-8ed419a7-580a-49d3-852f-9dcc92dc8ac9.png)

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir, I have checked above security issue on acronis production

**Comment by IshantRevclerx** [comment]
@prashantjadhav92 sir, I have tried open the link provided in the above comment on acronis production and its showing an error shown in the screenshoot below.
![image](https://user-images.githubusercontent.com/92088937/191498606-c5e99370-9036-4bf2-8900-a9a12c9ea6f1.png)

![image](https://user-images.githubusercontent.com/92088937/191498711-1db7febf-9540-4066-acd2-e8c5f303b041.png)

**Kindly provide the user who is able to access the above link so that we can reproduce the above issue at are end.**

**Comment by prashantjadhav92** [comment]
I will ask the client to verify this again.
