### ISSUE TITLE
SEC-4455 - Endpoint allows to access all customers files. [/gallery/documents/[File_ID]/edit/edit]

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#138]
An endpoint allows to access all customers files like [ images, documents, videos, pdfs, etc]

Steps To Reproduce:
1. Login
2. Visit this URL https://partners.acronis.com/gallery/documents/[File_ID]/edit/edit
3. Type any file id in URL, then click view page source.

This is similar to the issue https://github.com/MindMatrix/SecurityTracker/issues/61

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I have checked the above security issue and during my testing I was not been able to access documents or other user (in same organization and in different organization) by following the mentioned steps. This issue along with images issue was fixed in ticket no. 61. 

Kindly provide some additional information or screen recording so that I can reproduce the above issue at my end.

**Comment by prashantjadhav92** [comment]
I have asked the client to check again and provide the steps.

**Comment by prashantjadhav92** [comment]
Follow up sent to the client.

**Comment by prashantjadhav92** [comment]
Confirmed this is fixed.
