### ISSUE TITLE
#1450085 IDOR allows to copy other organizations’ social media post/drip, /api/DeletePublishings

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#46]
In the request to /api/DeletePublishings it is possible to specify media ID of media from any other organization. This media will be deleted

**Comment by IshantRevclerx** [comment]
@shaileshtayde sir , I have Checked above Issue. this issue is exist.
If one user in other organization that can be delete the drip of other organization.
![Delete Drip-1](https://user-images.githubusercontent.com/92088937/173362266-ec4b03d5-719e-4d4a-bd49-736d4ea136fa.png)

![Delete Drip-2](https://user-images.githubusercontent.com/92088937/173362463-0820b07f-5987-4c24-9e9b-a8d3cc9e5396.png)

**Comment by IshantRevclerx** [comment]
@shaileshtayde  sir, The above Issue is not for Normal user.

**Comment by shaileshtayde** [comment]
@prashantjadhav92 as @shivmishra & @PuneetRevclerx confirmed, these issues are not reproduceable for users having proper permissions.
@prashantjadhav92 Please confirm what users they are trying with? if it is SuperAdmin, it will work.

**Comment by prashantjadhav92** [comment]
@shaileshtayde Acronis is not using a super admin user to test this. I have requested them for the steps.
