### ISSUE TITLE
SEC-3854 XSS in Landing Pages

### ISSUE THREAD

**Issue by prashantjadhav92** [MindMatrix/SecurityTracker#59]
It is possible to insert scripts in Landing Pages during their customization. This issue was already reported, but was not fully fixed, since the vulnerable field was just hidden on the frontend.

Steps to reproduce:
    a. Open customization for any landing page and go to Landing page Editor -> Page Settings -> Meta Information
    b. Open browser Developer Tools -> Inspector. In Inspector search for "Scripts and Styling". In enclosing div element remove style="display: none;"
    c. Insert any script in "Scripts and Styling" field which should now be visible, e.g. <script>alert(1)</script>
    d. Finish landing page customization and get the link
    e. Open the link and see JavaScript payload executed

Fix: It is not enough to hide the field, it should be completely removed, in API as well

**Comment by PuneetRevclerx** [comment]
@shaileshtayde sir, I have verified the above mentioned issue on "dvl-main" and "mm live":

**Point 1:** It is possible to remove style="display: none;" for "Scripts and Styling" and see the field on UI which is otherwise hidden on both  "dvl-main" and "mm live".

**Point 2:** After inserting the script in "Scripts and Styling" filed, if we open the link:

- On "dvl-main" alert message does not show up:

![alert message main](https://user-images.githubusercontent.com/102346181/173012268-718a86a5-6a0f-4f93-be26-bd5b91f6a6b0.png)

- But, on "mm live" JavaScript payload gets executed and alert message shows up:

![alert message live](https://user-images.githubusercontent.com/102346181/173012462-262a7998-21b0-4fce-9b8a-6f4baf0ce76a.png)

**Comment by PuneetRevclerx** [comment]
Now, facing above issue on main as well.

**Comment by sunrao** [comment]
@Vish-Patil Pl. get this done

**Comment by Vish-Patil** [comment]
please get this tested in following PR -53840

**Comment by PuneetRevclerx** [comment]
@sunrao sir, @Vish-Patil sir, I have checked above security issue on the given branch (https://pr-53840.dvl.amp.vg/) and it's working as expected now.

**Comment by Vish-Patil** [comment]
@sunrao please get this tested by executing API directly as well.

**Comment by PuneetRevclerx** [comment]
@sunrao sir, +1

**Comment by PuneetRevclerx** [comment]
@prashantjadhav92 sir, I checked the above security issue on Acronis Production and it's working as expected.

**Comment by prashantjadhav92** [comment]
I have asked the client to verify.

**Comment by prashantjadhav92** [comment]
Client confirmed the ticket can be closed.
